language: c++
python:
  - "2.7"
compiler:
  - gcc
sudo: required
dist: trusty
services:
  - docker
env:
  global:
    - USE_TRAVIS=true
  matrix:
    - ROS_DISTRO=hydro   USE_DEB=true USE_DOCKER=true
    - ROS_DISTRO=indigo  USE_DEB=true
    - ROS_DISTRO=jade    USE_DEB=true
    - ROS_DISTRO=kinetic USE_DEB=true USE_DOCKER=true
script: source .travis/travis.sh
notifications:
  email:
    on_success: always
    on_failure: always
